### ISSUE TITLE
Setting up a website for this.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/collaboration#1]
https://collaboration.darwinia.network.

**Comment by nblogist** [comment]
hey @HackFisher  this seems down https://collaboration.darwinia.network/

**Comment by 1022ranji** [comment]
Now the corresponding Grant button on Darwinia and Crab will jump directly to here: [https://github.com/darwinia-network/collaboration/blob/master/grant/README.md](https://github.com/darwinia-network/collaboration/blob/master/grant/README.md)
Maybe we no longer need to create a separate Domain for this.
