### ISSUE TITLE
Program Status

### ISSUE THREAD

**Issue by 7flash** [darwinia-network/collaboration#24]
Still active?

**Comment by 1022ranji** [comment]
This repo (https://github.com/darwinia-network) is open-source, and you can find frequent updates here, indicating the latest developments of the project.

For more information, please refer to:
Website: https://darwinia.network/
Medium: https://medium.com/darwinianetwork
Docs: https://docs.darwinia.network/
Darwinia Genepaper: https://darwinia.network/Genepaper_v3.pdf
Darwinia Optimistic Bridge - Sublinear Relay For Interoperable Blockchains: https://darwinia.network/itering_io_optimistic_bridge_technical_paper_en.pdf
