### ISSUE TITLE
Adding collaboration category of service providers.

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/collaboration#38]
Will request the service provider to provide invoice/payment info before execution.

For reasons of commercial confidentiality and privacy, the PDF file can be shared as a Google document, encrypted, and only among collaboration management members. However, the process of reviewing related PDF links and requests should utilize the GitHub Repo PR to help establish a management process in the ecosystem.

**Comment by wuminzhe** [comment]
https://github.com/darwinia-network/collaboration/blob/662aa9fd638004d30b48051ebba53b6c12e19dc0/service-providers/itering.md

**Comment by hackfisher** [comment]
@wuminzhe Please give readme guiding other contributors, e.g. the Invoice need to be in encrypted PDF format.

**Comment by wuminzhe** [comment]
> @wuminzhe Please give readme guiding other contributors, e.g. the Invoice need to be in encrypted PDF format.

https://github.com/darwinia-network/collaboration/pull/44
